### ISSUE TITLE
examples/allen_cahn_causal.py缺少对应的config文件

### ISSUE THREAD

**Issue by pecanjk** [PaddlePaddle/PaddleScience#1103]
examples/allen_cahn_causal.py里使用的`allen_cahn_causal.yaml`缺失，有一个`allen_cahn_causal_fourier_rwf.yaml`文件，是命名有误？

**Comment by HydrogenSulfate** [comment]
不好意思， 是我忘记上传了，在 #1104 PR中上传

**Comment by pecanjk** [comment]
> 不好意思， 是我忘记上传了，在 [#1104](https://github.com/PaddlePaddle/PaddleScience/pull/1104) PR中上传

目前这个allen_cahn_causal.yaml得到结果不好(u_validator/L2Rel.u: 0.51113)，需要把model setting部分设置fourier,random_weight才可以得到好的结果(u_validator/L2Rel.u: 0.00280)
``` yaml
MODEL:
  input_keys: [t, x]
  output_keys: [u]
  num_layers: 4
  hidden_size: 256
  activation: tanh
  periods:
    x: [2.0, false]
  fourier:
    dim: 256
    scale: 1.0
  random_weight:
    mean: 0.5
    std: 0.1
```
